#!/usr/bin/env bash

set -xe

mkdir -p 'tmp/bin'
pushd 'tmp/bin'
rm -rf 'rubyfmt'
git clone git@github.com:fables-tales/rubyfmt.git
pushd 'rubyfmt'
make all
popd
popd

gem install \
  rubocop \
  rufo \
  standard \
  syntax_tree \
  prettier
npm install --global prettier @prettier/plugin-ruby
